from typing import Annotated, List, Dict, Any, TypedDict
from langchain_core.messages import BaseMessage
import operator

class AgentMessage(TypedDict):
    sender: str
    content: str
    confidence: float
    citations: List[str]
    tool_calls: List[Dict[str, Any]]

class NexusState(TypedDict):
    # The history of messages in the conversation
    messages: Annotated[List[BaseMessage], operator.add]
    # The current agent being executed
    current_agent: str
    # Chunks retrieved from the vector store
    retrieved_chunks: List[Dict[str, Any]]
    # Number of iterations for reaching a consensus/validation
    iteration_count: int
    # Maximum allowed iterations
    max_iterations: int
    # Status of the validation (e.g., "approved", "rejected", "pending")
    validation_status: str
    # Score representing the detected hallucination level
    hallucination_score: float
    # Final answer generated by the analyst
    final_answer: str
    # List of detected PII entities
    pii_detected: List[str]
    # Query being processed
    query: str
    # Log of agent activities for UI visualization (node, status, timestamp)
    activity_log: Annotated[List[Dict[str, Any]], operator.add]
