import operator
from typing import Annotated, Any, TypedDict

from langchain_core.messages import BaseMessage


class AgentMessage(TypedDict):
    sender: str
    content: str
    confidence: float
    citations: list[str]
    tool_calls: list[dict[str, Any]]


class NexusState(TypedDict):
    # The history of messages in the conversation
    messages: Annotated[list[BaseMessage], operator.add]
    # The current agent being executed
    current_agent: str
    # Chunks retrieved from the vector store
    retrieved_chunks: list[dict[str, Any]]
    # Number of iterations for reaching a consensus/validation
    iteration_count: int
    # Maximum allowed iterations
    max_iterations: int
    # Status of the validation (e.g., "approved", "rejected", "pending")
    validation_status: str
    # Score representing the detected hallucination level
    hallucination_score: float
    # Final answer generated by the analyst
    final_answer: str
    # List of detected PII entities
    pii_detected: list[str]
    # Query being processed
    query: str
    # Log of agent activities for UI visualization (node, status, timestamp)
    activity_log: Annotated[list[dict[str, Any]], operator.add]
    # Current user ID for filtering retrieval
    user_id: str | None
    # Retrieval settings from Tune Engine
    match_threshold: float
    rerank: bool
    # New control fields for loop safety
    search_count: int
    is_greeting: bool
